version: "3"

services:
  app:
    build: .
    depends_on:
      - redis
    links:
      - redis
    command: npm run dev
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
  # pg:
  #   image: postgres
  #   environment:
  #     - POSTGRES_PASSWORD=nataia
  #     - POSTGRES_DB=edu-control
  #   ports:
  #     - "5432:5432"
