version: "3.9"

services:
  app:
    build: .
    ports:
      - "3333:3333"
    links:
      - db
    command: npm run dev
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:nataia@db:5432/edu-control
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=nataia
      - POSTGRES_DB=edu-control
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
